apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openresty.fullname" . }}
  labels:
    {{- include "openresty.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openresty.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openresty.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openresty.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.openresty.modules.enabled }}
      initContainers:
        - name: modules-init
          image: {{ include "openresty.image" . }}
          command:
            - /bin/sh
            - /tmp/install-modules.sh
          volumeMounts:
            - name: modules-script
              mountPath: /tmp/install-modules.sh
              subPath: install-modules.sh
            - name: lua-lib
              mountPath: /usr/local/openresty/lualib
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "openresty.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            {{- if .Values.service.https.enabled }}
            - name: https
              containerPort: {{ .Values.service.https.targetPort }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{- if .Values.openresty.lua.enabled }}
            - name: lua-scripts
              mountPath: /usr/local/openresty/lualib/custom
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /var/log/nginx
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "openresty.configMapName" . }}
        {{- if .Values.openresty.lua.enabled }}
        - name: lua-scripts
          configMap:
            name: {{ include "openresty.luaConfigMapName" . }}
        {{- end }}
        {{- if .Values.openresty.modules.enabled }}
        - name: modules-script
          configMap:
            name: {{ include "openresty.fullname" . }}-modules-script
        - name: lua-lib
          emptyDir: {}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "openresty.pvcName" . }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
