image:
  registry: docker.io
  repository: openresty/openresty
  tag: "1.25.3.1-alpine"
  pullPolicy: IfNotPresent

# Deployment replicas
replicaCount: 1

service:
  type: LoadBalancer
  port: 80

  https:
    port: 443
  annotations: {}

# Autoscaling (HPA)
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Resources limits/requests
resources:
  limits:
    cpu: 1000m
    memory: 4096Mi
  requests:
    cpu: 250m
    memory: 1024Mi

# Nginx configuration

luaScripts:
  {}
  # example:
  # my_script.lua: |
  #   local http = require "resty.http"
  #   -- Custom Lua code here

config:
  nginxConfig: |
    worker_processes auto;
    error_log /dev/stderr;
    events { worker_connections 1024; }
    http {
      include       mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;
      server {
        listen       80;
        server_name  _;
        location / {
          root   html;
          index  index.html index.htm;
        }
      }

      server {
        listen 443 ssl;
        server_name _;
        ssl_certificate /usr/local/openresty/nginx/data/cert.crt;
        ssl_certificate_key /usr/local/openresty/nginx/data/cert.key;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:10m;
        ssl_session_tickets off;

        location / {
          root   html;
          index  index.html index.htm;
        }
      }
    }

data:
  cert.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  cert.key: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----

# Pod annotations, labels, etc.
podAnnotations: {}
podLabels: {}
