apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  nginx.conf: |-
{{ .Values.config.nginxConfig | nindent 4 }}
{{- range $configName, $configValue := .Values.data }}
  {{ $configName }}: |-
{{ $configValue | nindent 4 }}
{{- end }}
{{- range $scriptName, $scriptValue := .Values.luaScripts }}
  {{ $scriptName }}: |-
{{ $scriptValue | nindent 4 }}
{{- end }}