{{- if .Values.openresty.modules.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openresty.fullname" . }}-modules-init
  labels:
    {{- include "openresty.labels" . | nindent 4 }}
data:
  install-modules.sh: |
    #!/bin/bash
    set -e
    
    echo "Installing Lua modules..."
    
    # Install luarocks modules
    {{- if .Values.openresty.modules.luarocks }}
    {{- range .Values.openresty.modules.luarocks }}
    echo "Installing {{ . }} via luarocks..."
    luarocks install {{ . }}
    {{- end }}
    {{- end }}
    
    # Install Git modules
    {{- if .Values.openresty.modules.gitModules }}
    {{- range .Values.openresty.modules.gitModules }}
    echo "Installing {{ .name }} from {{ .url }}..."
    git clone {{ .url }} /tmp/{{ .name }}
    mkdir -p {{ .path }}
    cp -r /tmp/{{ .name }}/* {{ .path }}/
    rm -rf /tmp/{{ .name }}
    {{- end }}
    {{- end }}
    
    echo "Lua modules installation completed!"
    
    # Set proper permissions
    chown -R nginx:nginx /usr/local/openresty/lualib/
    chmod -R 755 /usr/local/openresty/lualib/
{{- end }}
