apiVersion: v1
kind: Service
metadata:
  name: {{ include "openresty.fullname" . }}
  labels:
    {{- include "openresty.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.https.enabled }}
    - port: {{ .Values.service.https.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "openresty.selectorLabels" . | nindent 4 }}
